# Generated by Django 4.2.4 on 2023-08-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='employee_name')),
                ('surname', models.CharField(max_length=50, verbose_name='employee_surname')),
                ('patronymic', models.CharField(blank=True, max_length=50, null=True, verbose_name='employee_patronymic')),
                ('position', models.CharField(max_length=100, verbose_name='employee_position')),
                ('employment_date', models.DateTimeField(verbose_name='employment_date')),
                ('dismissal_date', models.DateTimeField(blank=True, null=True, verbose_name='dismissal_date')),
                ('is_active', models.BooleanField(verbose_name='is_employee_active')),
            ],
        ),
    ]
