# Generated by Django 4.2.4 on 2023-09-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_remove_employee_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is_employee_active'),
            preserve_default=False,
        ),
    ]
