# Generated by Django 4.2.4 on 2023-08-29 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='task_title')),
                ('description', models.TextField(verbose_name='task_description')),
                ('status', models.CharField(choices=[('created', 'Created'), ('in_progress', 'In_progress'), ('done', 'Done')], default='created', max_length=11, verbose_name='task_status')),
                ('deadline', models.DateTimeField(verbose_name='task_deadline')),
                ('is_active', models.BooleanField(default=True, verbose_name='task_activity_flag')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='task_executor', to='employees.employee', verbose_name='task_executor')),
            ],
        ),
    ]
