# Generated by Django 4.2.4 on 2023-08-31 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_options_alter_employee_dismissal_date_and_more'),
        ('tasks', '0005_alter_task_executor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='executor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='executor_tasks', to='employees.employee', verbose_name='task_executor'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In_progress'), ('done', 'Done')], default='created', max_length=11, verbose_name='task_status'),
        ),
    ]
