# Generated by Django 4.2.4 on 2023-08-31 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_executor_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('in_progress', 'In_progress'), ('done', 'Done')], default='created', max_length=11, verbose_name='task_status'),
        ),
    ]
