# Generated by Django 4.2.4 on 2023-08-31 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_task_executor'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='execution_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='execution_date'),
        ),
        migrations.AddField(
            model_name='task',
            name='in_progres_from',
            field=models.DateTimeField(blank=True, null=True, verbose_name='in_progres_from'),
        ),
    ]
