# Generated by Django 4.2.4 on 2023-09-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_task_execution_date_task_in_progres_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is_active'),
        ),
    ]
